name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - aiohttp
  - boto3
  - exifread
  - flask
  - h5netcdf
  - netcdf4
  - pip
  - pydap
  - pytest
  - rasterio
  - s3fs
  - scikit-image
  - rangehttpserver
  - xarray
  - zarr
  - moto
  - s3fs
  - rioxarray
  - werkzeug
  - dask
  - numpy <2
  - pip:
      - git+https://github.com/intake/intake
