name: test_env
channels:
  - conda-forge
dependencies:
  - python
  - aiohttp
  - boto3
  - flask
  - h5netcdf
  - intake
  - netcdf4
  - pip
  - pydap
  - pytest
  - rasterio
  - s3fs
  - scikit-image
  - xarray
  - zarr
  - pip:
       - rangehttpserver
       - moto[s3]
