# Run a nightly test against unpinned conda environment
name: Cron

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: ${{ matrix.CONDA_ENV }}-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CONDA_ENV: [unpinned, upstream]    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: test_env
          environment-file: ci/environment-${{ matrix.CONDA_ENV }}.yml

      - name: Development Install intake-xarray
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
          conda list

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --verbose --ignore=intake_xarray/tests/test_network.py

      - name: Run Tests Requiring Network Connection
        shell: bash -l {0}
        run: |
          pytest --verbose intake_xarray/tests/test_network.py
