name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  test:
    name: ${{ matrix.CONDA_ENV }}-pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CONDA_ENV: [py312, py311, py310, py39, upstream]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup conda
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/environment-${{ matrix.CONDA_ENV }}.yml

      - name: Development Install Intake-Xarray
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
          conda list

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --verbose -s --ignore=intake_xarray/tests/test_network.py
